config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # Habilitar login rede sociais
  # devise_for :usuarios, controllers: {:omniauth_callbacks => "omniauth_callbacks"}
  devise_for :usuarios

  resources :usuarios, only: [:edit,:update]

  # Routes for RaroCrud
  get '/crud/:model' => "crud#index"
  get '/crud/:model/:id/edit' => "crud#edit"
  delete '/crud/:model/:id/destroy' => "crud#destroy"
  get '/crud/:model/new' => "crud#new"
  get '/crud/:model/query' => "crud#query"
  get '/crud/:model/autocomplete' => "crud#autocomplete"
  post '/crud/:model/create' => "crud#create"
  patch '/crud/:model/:id/create' => "crud#create"
  get '/crud/:model/:id/acao/:acao' => "crud#action"
  get '/crud/:model/:id' => "crud#show"

  #Routes for RaroCrud Associations
  get '/crud/:model/:id/:associacao' => "crud#index"
  get '/crud/:model/:id/:associacao/:associacao_id/edit' => "crud#edit"
  delete '/crud/:model/:id/:associacao/:associacao_id/destroy' => "crud#destroy"
  get '/crud/:model/:id/:associacao/new' => "crud#new"
  get '/crud/:model/:id/:associacao/query' => "crud#query"
  get '/crud/:model/:id/:associacao/autocomplete' => "crud#autocomplete"
  post '/crud/:model/:id/:associacao/create' => "crud#create"
  patch '/crud/:model/:id/:associacao/:associacao_id/create' => "crud#create"
  get '/crud/:model/:id/:associacao/:associacao_id/acao/:acao' => "crud#action"
  get '/crud/:model/:id/:associacao/:associacao_id' => "crud#show"

  resources :permissoes, only: [:create]

  namespace :api do
    resources :cidades, only: [] do
      collection do
        get 'busca'
      end
    end
  end
end

app/views/papeis/_associar.html.erb
<%= render_crud do %>
<div class="widget-box">
	<div class="widget-body">
		<div class="widget-main">
			<%= form_tag permissoes_path, method: :post, class: "form-horizontal" do |f| %>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Descrição</th>
						<th width="5%">Visualizar</th>
						<th width="5%">Criar</th>
						<th width="5%">Editar</th>
						<th width="5%">Excluir</th>
						<th width="5%">Todos</th>
					</tr>
				</thead>
				<tbody>
					<% raro_permissions.each_with_index do |menu, i| %>
					<% val = nil %>
					<% if @record.permissoes.present? %>
						<% val = @record.permissoes.select {|c| c.klass.to_s == menu.to_s }[0] %>
					<% end %>
					<tr>
						<td><%= menu.titleize %></td>
						<td>
							<div class="checkbox i-checks text-center checkbox-permission">
								<input id="view_<%= i %>" name="papel[permissoes_attributes][<%= i %>][can_read]" type="checkbox" <%= (val.present? && val.can_read) ? 'checked' : '' %>>
							</div>
						</td>
						<td>
							<div class="checkbox i-checks text-center checkbox-permission">
								<input id="create_<%= i %>" name="papel[permissoes_attributes][<%= i %>][can_create]" type="checkbox" <%= (val.present? && val.can_create) ? 'checked' : '' %>>
							</div>
						</td>
						<td>
							<div class="checkbox i-checks text-center checkbox-permission">
								<input id="edit_<%= i %>" name="papel[permissoes_attributes][<%= i %>][can_update]" type="checkbox" <%= (val.present? && val.can_update) ? 'checked' : '' %>>
							</div>
						</td>
						<td>
							<div class="checkbox i-checks text-center checkbox-permission">
								<input id="destroy_<%= i %>" name="papel[permissoes_attributes][<%= i %>][can_destroy]" type="checkbox" <%= (val.present? && val.can_destroy) ? 'checked' : '' %>>
							</div>
						</td>
						<td>
							<div class="checkbox i-checks text-center checkbox-permission">
								<input id="all_<%= i %>" name="papel[permissoes_attributes][<%= i %>][can_manage]" type="checkbox" <%= (val.present? && val.can_manage) ? 'checked' : '' %>>
							</div>
						</td>
						<%= hidden_field_tag "papel[permissoes_attributes][#{i}][klass]", menu %>
					</tr>
					<% end %>
				</tbody>
			</table>
			<%= hidden_field_tag :papel_id, @record.id %>
			<div class="form-group">
				<div class="col-sm-12">
					<div class="col-sm-offset-2 pull-right">
						<%= render_default_actions_crud %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>
<% end %>
<% content_for :javascript do %>
<script type="text/javascript">
	$(function() {
		permission();
	});
</script>
<% end %>