config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # Habilitar login rede sociais
  # devise_for :usuarios, controllers: {:omniauth_callbacks => "omniauth_callbacks"}
  devise_for :usuarios

  resources :usuarios, only: [:edit,:update]

  # Routes for RaroCrud
  get '/crud/:model' => "crud#index"
  get '/crud/:model/:id/edit' => "crud#edit"
  delete '/crud/:model/:id/destroy' => "crud#destroy"
  get '/crud/:model/new' => "crud#new"
  get '/crud/:model/query' => "crud#query"
  get '/crud/:model/autocomplete' => "crud#autocomplete"
  post '/crud/:model/create' => "crud#create"
  patch '/crud/:model/:id/create' => "crud#create"
  get '/crud/:model/:id/acao/:acao' => "crud#action"
  get '/crud/:model/:id' => "crud#show"

  #Routes for RaroCrud Associations
  get '/crud/:model/:id/:associacao' => "crud#index"
  get '/crud/:model/:id/:associacao/:associacao_id/edit' => "crud#edit"
  delete '/crud/:model/:id/:associacao/:associacao_id/destroy' => "crud#destroy"
  get '/crud/:model/:id/:associacao/new' => "crud#new"
  get '/crud/:model/:id/:associacao/query' => "crud#query"
  get '/crud/:model/:id/:associacao/autocomplete' => "crud#autocomplete"
  post '/crud/:model/:id/:associacao/create' => "crud#create"
  patch '/crud/:model/:id/:associacao/:associacao_id/create' => "crud#create"
  get '/crud/:model/:id/:associacao/:associacao_id/acao/:acao' => "crud#action"
  get '/crud/:model/:id/:associacao/:associacao_id' => "crud#show"

  resources :permissoes, only: [:create]

  namespace :api do
    resources :cidades, only: [] do
      collection do
        get 'busca'
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
		<a href="http://www.rarolabs.com.br">
			<%=image_tag(Templus.logo_rodape, height: '20px') %>
		</a>
  </div>
  <strong>RaroLabs</strong> &copy; 2010-<%= DateTime.now.strftime("%Y") %>
</footer>

app/views/layouts/_menu.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
			<%= menu_crud_helper(UsuarioCrud.title, Usuario, 'fa fa-user') %>
      <%= menu_crud_helper(PapelCrud.title, Papel, 'fa fa-lock') %>
      <!--Grupo -->
      <!-- <li class="header">MAIN NAVIGATION</li>

      <li class="treeview active">
        <a href="#">
          <i class="fa fa-files-o"></i>
          <span>Layout Options</span>
          <span class="label label-primary pull-right">4</span>
        </a>
        <ul class="treeview-menu">
          <li><a href="../layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
          <li><a href="../layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
          <li class="active"><a href="../layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
          <li><a href="collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
        </ul>
      </li>

      <li>
        <a href="../widgets.html">
          <i class="fa fa-th"></i> <span>Widgets</span> <small class="label pull-right bg-green">new</small>
        </a>
      </li>
       -->
      <!-- <li class="treeview">
        <a href="#">
          <i class="fa fa-share"></i> <span>Multilevel</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          <li>
            <a href="#"><i class="fa fa-circle-o"></i> Level One <i class="fa fa-angle-left pull-right"></i></a>
            <ul class="treeview-menu">
              <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
              <li>
                <a href="#"><i class="fa fa-circle-o"></i> Level Two <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                  <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
        </ul>
      </li> -->
    </ul>
  </section>
</aside>

app/views/layouts/_template.html.erb
<section class="content-header">
  <h1>
		<% if content_for? :header %>
			<%= yield  :header %>
		<% end %>
  </h1>
	<ol class="breadcrumb">
		<li><a href="/">Home</a></li>
		<% if content_for? :breadcumb %>
		<%= yield  :breadcumb %>
		<% end %>
	</ol>
  
  <% if content_for? :scopes %>
    <div class='row' style='clear:both;'>
      <div class='col-xs-12'>
      	<%= yield  :scopes %>
      </div>
    </div>
  <% end %>
</section>

<section class="content">
	<% if content_for? :corpo %>
		<%= yield  :corpo %>
	<% end %>  
</section>

app/views/layouts/_template_raro_crud.html.erb
<%unless params[:render] == 'modal'%>
  <section class="content-header">
    <h1>
      <% if content_for? :header %>
        <%= yield  :header %>
      <% end %>
    </h1>
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <% if content_for? :breadcumb %>
        <%= yield  :breadcumb %>
      <% end %>
    </ol>
  
    <% if content_for? :scopes %>
    <div class='row m-t-md'>
      <%= yield  :scopes %>
    </div>
    <% end %>
  </section>
  <section class="content">
    <% if content_for? :corpo %>
      <%= yield  :corpo %>
    <% end %>
  </section>
<% else %>
  <% if content_for? :corpo %>
    <%= yield  :corpo %>
  <% end %>
<% end %>
<% if content_for? :modal %>
  <%= yield  :modal %>
<% end %>

app/views/layouts/_topnavbar.html.erb
<header class="main-header">
  <!-- Logo -->
	<%= link_to root_path, class: 'logo' do %>
    <span class='logo-mini'><%=image_tag(Templus.logo_menor)%></span>
		<span class="logo-lg"><%=image_tag(Templus.logo)%></span>	
	<% end %>
  
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Alternar navegação</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag 'user2-160x160.jpg', class: 'user-image' %>
            <span class="hidden-xs"><%= current_usuario.to_s %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag 'user2-160x160.jpg', class: 'img-circle' %>
              <p>
                <%= current_usuario.to_s %>
                <small>Membro desde <%= RaroUtil.formata_data(current_usuario.created_at, "%B de %Y") %></small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to 'Profile', edit_usuario_path(current_usuario), class: 'btn btn-default btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to 'Sair', destroy_usuario_session_path, data: {method: :delete}, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title><%=Templus.nome_aplicacao%> | <%=Templus.nome_empresa%> </title>
    <%= favicon_link_tag Templus.favicon %>
    <!-- Main css styles -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Main javascript files -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>
  <body class="hold-transition skin-blue fixed sidebar-mini" data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <!-- Skin configuration box -->
    <!-- Wrapper-->
    <div class="wrapper">
      <!-- Navigation -->
      <%= render 'layouts/topnavbar' %>

      <%= render 'layouts/menu' %>

      <div class="content-wrapper <%= @extra_class %>">
        <%= flash_messages_for %>

        <div id="page-wrapper-main">
          <%= yield %>
        </div>
      </div>

      <%= render 'layouts/footer' %>
    </div>

    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/forgot_password.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%=Templus.nome_aplicacao%> | <%=Templus.nome_empresa%> </title>
	<%= favicon_link_tag Templus.favicon %>
	<!-- Include style per-controller - vendor plugins -->
	<%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css.scss") %>
	<!-- Main css styles -->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<!-- Main javascript files -->
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= flash_messages_for %>
	<div class="middle-box text-center loginscreen  animated fadeInDown">
		<div>
			<div>
				<h1 class="logo-name">
					<%=image_tag(Templus.logo_landpage, class: 'img-responsive')%>
				</h1>
			</div>
			<%= yield %>
			<p class="m-t"> <small>RaroLabs &copy; 2010-<%= DateTime.now.year %></small> </p>
		</div>
	</div>
</div>
<!-- End wrapper-->

<!-- Include javascript per-controller - vendor plugins -->
<%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

<%= yield :javascript %>

</body>
</html>


app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  	<title><%=Templus.nome_aplicacao%> | <%=Templus.nome_empresa%> </title>
  	<%= favicon_link_tag Templus.favicon %>
  	<!-- Include style per-controller - vendor plugins -->
  	<%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css.scss") %>
  	<!-- Main css styles -->
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<!-- Main javascript files -->
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">
    <%= flash_messages_for %>
    <div class="login-box">
      <div class="login-logo">
        <%= image_tag(Templus.logo_landpage)%>
      </div>
      <div class="login-box-body">
        <p class="login-box-msg">
          <%= Templus.paragrafo_login %>
        </p>
  			
        <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    			<div class="form-group">
    				<%= f.input_field :email, :required => false, class:"form-control", :placeholder => "Email" %>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    			</div>
    			<div class="form-group">
    				<%= f.input_field :password, :required => false, class:"form-control", :placeholder => "Senha" %>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    			</div>
          <div class="row">
            <div class="col-xs-12 text-center">
              <%= f.button :submit, "Login", class: 'btn btn-primary btn-block btn-flat' %>
            </div>
          </div>
        
          <!-- /.social-auth-links -->
          <!-- <div class="social-auth-links text-center">
            <p>- OU -</p>
            <%#= link_to usuario_omniauth_authorize_path(:facebook), class: 'btn btn-block btn-social btn-facebook btn-flat' do %>
              <i class='fa fa-facebook'></i> Login via Facebook
            <%# end %>
          </div> -->
				<% end %>
      </div>
      <div class="login-box-footer">
        <small>RaroLabs &copy; 2010-<%= Date.today.year %></small>
      </div>
    </div>

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <%= yield :javascript %>

  </body>
</html>


app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  	<title><%=Templus.nome_aplicacao%> | <%=Templus.nome_empresa%> </title>
  	<%= favicon_link_tag Templus.favicon %>
  	<!-- Include style per-controller - vendor plugins -->
  	<%= stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css.scss") %>
  	<!-- Main css styles -->
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<!-- Main javascript files -->
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition register-page">
    <%= flash_messages_for %>
    <div class="register-box">
      <div class="register-logo">
        <%= image_tag(Templus.logo_landpage)%>
      </div>

      <div class="register-box-body">
        <p class="login-box-msg">Informe seus dados para criar um novo usuário</p>
  			<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  				<%= flash_messages_error(f.object.errors) %>
  				<div class="form-group">
  					<%= f.input_field :nome, :required => false, class:"form-control", :placeholder => "Nome" %>
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
  				</div>
  				<div class="form-group">
  					<%= f.input_field :email, :required => false, class:"form-control", :placeholder => "Email" %>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
  				</div>
  				<div class="form-group">
  					<%= f.input_field :password, :required => false, class:"form-control", :placeholder => "Senha" %>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
  				</div>
  				<div class="form-group">
  					<%= f.input_field :password_confirmation, :required => false, class:"form-control", :placeholder => "Confirmação de senha" %>
            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
  				</div>
          <div class="row">
            <div class="col-xs-12 text-center">
              <%= f.button :submit, "Registrar", class: 'btn btn-primary btn-block btn-flat' %>
            </div>
          </div>  
  			<% end %>
        
        <!-- <div class="social-auth-links text-center">
          <p>- OU -</p>
          <%#= link_to usuario_omniauth_authorize_path(:facebook), class: 'btn btn-block btn-social btn-facebook btn-flat' do %>
            <i class='fa fa-facebook'></i> Registro via Facebook
          <%# end %>
        </div> -->
      </div>
      <div class="register-box-footer">
        <%= link_to 'Acesso ao sistema', new_usuario_session_path %>
      </div>
    </div>

    <!-- Include javascript per-controller - vendor plugins -->
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>

    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/wiselinks.html.erb
<%= yield :menu %>
<%= yield %>
<%= yield :scripts %>
<div id="modal-element">
</div>